INSERT INTO clubs (name) VALUES
('CRO'),
('SPA'),
('SRB'),
('BRA'),
('CHN'),
('AUS'),
('GRE'),
('HUN'),
('MNE'),
('USA'),
('ITA'),
('RSA'),
('ROU'),
('JPN'),
('SGP'),
('CAN');

INSERT INTO players (name, position, club_id) VALUES
('Franko Lazic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Toni Popadic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Luka Loncar', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Bernat Sanahuja', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Marc Larumbe', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Eduardo Lorrio', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Petar Jaksic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Marko Zuvela', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Vuk Milojevic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Vasilije Martinovic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Joao Pedro Serra', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Deming Li', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Jiahao Peng', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Yuhao Cai', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Jiashao Zhu', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Zijun Wen', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Yongxiang Wu', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Beiyi Wang', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Zhilong Liu', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Yu Liu', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Tin Brubnjak', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Laurence Barker', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Drew McJannett', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Sam Nangle', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Tristan Glanznig', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Andrej Grgurevic', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Tim Putt', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Nathan Power', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Matthew Byrnes', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Marcus Berehulak', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Dingsong Shen', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Konstaninos Genidounias', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Aristides Chalyvopoulos', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Csoma Kristof', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Angyal Daniel', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Manhercz Krisztian', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Molnar Erik', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Vamos Marton', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Nagy Adam', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Evangelos Pouros', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Fekete Gergo', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Burian Gergely', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Kovacs Peter', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Konstantin Kharkov', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Loren Fatovic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Alvaro Granados', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Sergi Cabanas', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Felipe Perrone', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Alberto Munarriz', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Efstathios Kalogeropoulos', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Dusan Banicevic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Ryder Dodd', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Hannes Daube', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Lazar Andric', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Dimitrije Obradovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Miguel De Toro', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Dmitrii Kholod', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Bernardo Herzer', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Jack Larsen', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Dominic Brown', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Jacob Ehrhardt', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Boris Vapenski', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Nikolaos Gkillas', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Luca Damonte', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Giacomo Cannella', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Jose Javier Bustos', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Lazar Dobozanov', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Logan Cabral', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Lucas de Oliveira', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Luis Ricardo Silva', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Gustavo Guimaraes', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Joao Gabriel Silveira', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Andre Luiz de Freitas', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Gabriel Sojo da Silva', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Marcos Pedroso', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Gustavo Coutinho', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Rino Buric', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Unai Biel', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Unai Aguirre', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Alejandro Bustos', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Filip Krzic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Angus Lambie', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Rui Chen', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Jacob Mercep', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Milos Maksimovic', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Charlie Negus', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Luka Bukic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Matias Biljaka', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Nic Porter', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Luke Pavillard', 'field', (SELECT id FROM clubs WHERE name = 'AUS' LIMIT 1)),
('Dimitrios Skoumpakis', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Konstantinos Gkiouvetsis', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Stylianos Argyropoulos', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Konstantinos Kakaris', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Dimitrios Nikolaidis', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Yimin Chen', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Panagiotis Tzortzatos', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Pedro Real', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Honghui Wu', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Zekai Xie', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Zhongxian Chen', 'field', (SELECT id FROM clubs WHERE name = 'CHN' LIMIT 1)),
('Nikolaos Papanikolaou', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Emmanouil Andreadis', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Nikolaos Gardikas', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1)),
('Marko Bijac', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Josip Vrlic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Zvonimir Butic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Ante Vukicevic', 'field', (SELECT id FROM clubs WHERE name = 'CRO' LIMIT 1)),
('Tommaso Baggi Necchi', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Mario Del Basso', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Francesco Cassia', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Filippo Ferrero', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Nikola Murisic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Calvin Kuperis', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Carl Germishuys', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Brett Sneddon', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Dylan Watt', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Dean Sneddon', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Kelly Geldenhuys', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Luka Rajak', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Manqoba Bungane', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Matthew Bowers', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Ryan Sneddon', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Tristan Grimett', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Themba Mthembu', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Nathan Ward', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Alessandro Velotto', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Tommaso Gianazza', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Francesco Condemi', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Connor Ohl', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Chase Dodd', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('PLayer1', 'field', (SELECT id FROM clubs WHERE name = 'ROU' LIMIT 1)),
('PLayer2', 'field', (SELECT id FROM clubs WHERE name = 'JPN' LIMIT 1)),
('PLayer3', 'field', (SELECT id FROM clubs WHERE name = 'SGP' LIMIT 1)),
('PLayer4', 'field', (SELECT id FROM clubs WHERE name = 'CAN' LIMIT 1)),
('Gianmarco Nicosia', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Nicholas Presciutti', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Dusan Mandic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Francesco Di Fulvio', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Lorenzo Bruni', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Edoardo Di Somma', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Matteo Iocchi Gratta', 'field', (SELECT id FROM clubs WHERE name = 'ITA' LIMIT 1)),
('Matthew Neser', 'field', (SELECT id FROM clubs WHERE name = 'RSA' LIMIT 1)),
('Fran Valera', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Strahinja Rasovic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Sava Randjelovic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Milos Cuk', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Nemanja Vico', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Radoslav Filipovic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Viktor Rasovic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Nikola Jaksic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Joao Pedro Leime', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Lucas Farias', 'field', (SELECT id FROM clubs WHERE name = 'BRA' LIMIT 1)),
('Dusan Matkovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Miroslav Perkovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Vigvari Vendel', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Jansik Szilard', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Vigvari Vince', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Mizsei Marton', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Vismeg Zsombor', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Nagy Akos', 'field', (SELECT id FROM clubs WHERE name = 'HUN' LIMIT 1)),
('Petar Tesanovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Dylan Woodhead', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Marko Vavic', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Adrian Weinberg', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Max Irving', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Vasilije Radovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Biel Gomila', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Djuro Radovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Aljosa Macic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Jovan Vujovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Djordje Lazic', 'field', (SELECT id FROM clubs WHERE name = 'SRB' LIMIT 1)),
('Ben Liechty', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Nicolas Saveljic', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Ryan Ohl', 'field', (SELECT id FROM clubs WHERE name = 'USA' LIMIT 1)),
('Strahinja Gojkovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Balsa Vuckovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Filip Gardasevic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Savo Cetkovic', 'field', (SELECT id FROM clubs WHERE name = 'MNE' LIMIT 1)),
('Roger Tahull', 'field', (SELECT id FROM clubs WHERE name = 'SPA' LIMIT 1)),
('Ioannis Alafragkis', 'field', (SELECT id FROM clubs WHERE name = 'GRE' LIMIT 1))
;
